name: torch-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - torch
      - transformers
      - numpy
      - pandas
      - wordcloud
      - matplotlib
      - plotly
      - huggingface_hub
      - openpyxl
      - hf_xet
      - datasets