[theme]
primaryColor = "#00CC88"

[theme.light]
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 10

[client]
showErrorDetails = false
toolbarMode = "viewer"